name = "VPalm"
uuid = "a7330139-cd8c-4ed3-8339-744bb7ed6d51"
authors = ["Rémi Vezy <VEZY@users.noreply.github.com> and contributors"]
version = "0.0.1"

[deps]
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
MultiScaleTreeGraph = "dd4a991b-8a45-4075-bede-262ee62d5583"
PlantGeom = "5edaa67e-25db-4eb9-bf81-05d793b2238d"

[compat]
julia = "1.9"
Meshes = "0.40"
MultiScaleTreeGraph = "0.12"
PlantGeom = "0.6"
